//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./BigQueryParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BigO.BigQuery.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BigQueryParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IBigQueryParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.statements_eof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements_eof([NotNull] BigQueryParser.Statements_eofContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.statement_eof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_eof([NotNull] BigQueryParser.Statement_eofContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] BigQueryParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] BigQueryParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.ddl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDdl_statement([NotNull] BigQueryParser.Ddl_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.dml_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDml_statement([NotNull] BigQueryParser.Dml_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.insert_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_statement([NotNull] BigQueryParser.Insert_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] BigQueryParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.delete_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelete_statement([NotNull] BigQueryParser.Delete_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.truncate_table_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTruncate_table_statement([NotNull] BigQueryParser.Truncate_table_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.update_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_statement([NotNull] BigQueryParser.Update_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.update_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_item([NotNull] BigQueryParser.Update_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.update_items"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_items([NotNull] BigQueryParser.Update_itemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.merge_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMerge_statement([NotNull] BigQueryParser.Merge_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.when_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhen_clause([NotNull] BigQueryParser.When_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.matched_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatched_clause([NotNull] BigQueryParser.Matched_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.not_matched_by_target_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_matched_by_target_clause([NotNull] BigQueryParser.Not_matched_by_target_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.not_matched_by_source_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_matched_by_source_clause([NotNull] BigQueryParser.Not_matched_by_source_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.merge_update_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMerge_update_clause([NotNull] BigQueryParser.Merge_update_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.merge_insert_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMerge_insert_clause([NotNull] BigQueryParser.Merge_insert_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.merge_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMerge_input([NotNull] BigQueryParser.Merge_inputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.dcl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDcl_statement([NotNull] BigQueryParser.Dcl_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.grant_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrant_statement([NotNull] BigQueryParser.Grant_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.resource_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource_type([NotNull] BigQueryParser.Resource_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.revoke_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRevoke_statement([NotNull] BigQueryParser.Revoke_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.procedural_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedural_statement([NotNull] BigQueryParser.Procedural_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.exception_when_error"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitException_when_error([NotNull] BigQueryParser.Exception_when_errorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.export_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExport_statement([NotNull] BigQueryParser.Export_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.load_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoad_statement([NotNull] BigQueryParser.Load_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.assert_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssert_statement([NotNull] BigQueryParser.Assert_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare([NotNull] BigQueryParser.DeclareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] BigQueryParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.execute_immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_immediate([NotNull] BigQueryParser.Execute_immediateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.begin_end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBegin_end([NotNull] BigQueryParser.Begin_endContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.begin_exception_end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBegin_exception_end([NotNull] BigQueryParser.Begin_exception_endContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.case_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_([NotNull] BigQueryParser.Case_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.case_search_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_search_expression([NotNull] BigQueryParser.Case_search_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] BigQueryParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] BigQueryParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop([NotNull] BigQueryParser.LoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat([NotNull] BigQueryParser.RepeatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] BigQueryParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.for_in"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_in([NotNull] BigQueryParser.For_inContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.begin_transaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBegin_transaction([NotNull] BigQueryParser.Begin_transactionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.commit_transaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommit_transaction([NotNull] BigQueryParser.Commit_transactionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.rollback_transaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRollback_transaction([NotNull] BigQueryParser.Rollback_transactionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.raise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaise([NotNull] BigQueryParser.RaiseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] BigQueryParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.query_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_statement([NotNull] BigQueryParser.Query_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table([NotNull] BigQueryParser.Create_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_table_like"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_like([NotNull] BigQueryParser.Create_table_likeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_table_copy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_copy([NotNull] BigQueryParser.Create_table_copyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_snapshot_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_snapshot_table([NotNull] BigQueryParser.Create_snapshot_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_table_clone"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_clone([NotNull] BigQueryParser.Create_table_cloneContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_view([NotNull] BigQueryParser.Create_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_materialized_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_materialized_view([NotNull] BigQueryParser.Create_materialized_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_materialized_view_as_replica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_materialized_view_as_replica([NotNull] BigQueryParser.Create_materialized_view_as_replicaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_external_schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_external_schema([NotNull] BigQueryParser.Create_external_schemaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_external_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_external_table([NotNull] BigQueryParser.Create_external_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_name_schemas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_name_schemas([NotNull] BigQueryParser.Column_name_schemasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_name_schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_name_schema([NotNull] BigQueryParser.Column_name_schemaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_function([NotNull] BigQueryParser.Create_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.named_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamed_parameters([NotNull] BigQueryParser.Named_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.named_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamed_parameter([NotNull] BigQueryParser.Named_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_js_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_js_function([NotNull] BigQueryParser.Create_js_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_py_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_py_function([NotNull] BigQueryParser.Create_py_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_remote_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_remote_function([NotNull] BigQueryParser.Create_remote_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_aggregate_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_aggregate_function([NotNull] BigQueryParser.Create_aggregate_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.function_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_parameters([NotNull] BigQueryParser.Function_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_parameter([NotNull] BigQueryParser.Function_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_aggregate_js_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_aggregate_js_function([NotNull] BigQueryParser.Create_aggregate_js_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_table_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_function([NotNull] BigQueryParser.Create_table_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.table_function_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_function_parameters([NotNull] BigQueryParser.Table_function_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.table_function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_function_parameter([NotNull] BigQueryParser.Table_function_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_declarations([NotNull] BigQueryParser.Column_declarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_declaration([NotNull] BigQueryParser.Column_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_procedure([NotNull] BigQueryParser.Create_procedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.procedure_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_arguments([NotNull] BigQueryParser.Procedure_argumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.procedure_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_argument([NotNull] BigQueryParser.Procedure_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_stored_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_stored_procedure([NotNull] BigQueryParser.Create_stored_procedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_row_access_policy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_row_access_policy([NotNull] BigQueryParser.Create_row_access_policyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_capacity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_capacity([NotNull] BigQueryParser.Create_capacityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_reservation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_reservation([NotNull] BigQueryParser.Create_reservationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_assignment([NotNull] BigQueryParser.Create_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_search_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_search_index([NotNull] BigQueryParser.Create_search_indexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.columns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumns([NotNull] BigQueryParser.ColumnsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn([NotNull] BigQueryParser.ColumnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_vector_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_vector_index([NotNull] BigQueryParser.Create_vector_indexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_schema_set_default_collate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_schema_set_default_collate([NotNull] BigQueryParser.Alter_schema_set_default_collateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_schema_set_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_schema_set_options([NotNull] BigQueryParser.Alter_schema_set_optionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_schema_add_replica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_schema_add_replica([NotNull] BigQueryParser.Alter_schema_add_replicaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_schema_drop_replica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_schema_drop_replica([NotNull] BigQueryParser.Alter_schema_drop_replicaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_set_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_set_options([NotNull] BigQueryParser.Alter_table_set_optionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_add_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_add_column([NotNull] BigQueryParser.Alter_table_add_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_add_foreign_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_add_foreign_key([NotNull] BigQueryParser.Alter_table_add_foreign_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.add_foreign_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_foreign_key([NotNull] BigQueryParser.Add_foreign_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_add_primary_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_add_primary_key([NotNull] BigQueryParser.Alter_table_add_primary_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_rename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_rename([NotNull] BigQueryParser.Alter_table_renameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_rename_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_rename_column([NotNull] BigQueryParser.Alter_table_rename_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.rename_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRename_column([NotNull] BigQueryParser.Rename_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_to_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_to_column([NotNull] BigQueryParser.Column_to_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_drop_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_drop_column([NotNull] BigQueryParser.Alter_table_drop_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_column([NotNull] BigQueryParser.Drop_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_drop_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_drop_constraint([NotNull] BigQueryParser.Alter_table_drop_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_drop_primary_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_drop_primary_key([NotNull] BigQueryParser.Alter_table_drop_primary_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_set_default_collate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_set_default_collate([NotNull] BigQueryParser.Alter_table_set_default_collateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_column_set_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_column_set_options([NotNull] BigQueryParser.Alter_table_column_set_optionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_column_drop_not_null"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_column_drop_not_null([NotNull] BigQueryParser.Alter_table_column_drop_not_nullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_column_set_data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_column_set_data_type([NotNull] BigQueryParser.Alter_table_column_set_data_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_column_set_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_column_set_default([NotNull] BigQueryParser.Alter_table_column_set_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_table_column_drop_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_column_drop_default([NotNull] BigQueryParser.Alter_table_column_drop_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_view([NotNull] BigQueryParser.Alter_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_materialized_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_materialized_view([NotNull] BigQueryParser.Alter_materialized_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_organization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_organization([NotNull] BigQueryParser.Alter_organizationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_project([NotNull] BigQueryParser.Alter_projectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_bi_capacity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_bi_capacity([NotNull] BigQueryParser.Alter_bi_capacityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_capacity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_capacity([NotNull] BigQueryParser.Alter_capacityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.alter_reservation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_reservation([NotNull] BigQueryParser.Alter_reservationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.undrop_schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUndrop_schema([NotNull] BigQueryParser.Undrop_schemaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_schema([NotNull] BigQueryParser.Drop_schemaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_table([NotNull] BigQueryParser.Drop_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_snapshot_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_snapshot_table([NotNull] BigQueryParser.Drop_snapshot_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_external_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_external_table([NotNull] BigQueryParser.Drop_external_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_view([NotNull] BigQueryParser.Drop_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_materialized_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_materialized_view([NotNull] BigQueryParser.Drop_materialized_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_function([NotNull] BigQueryParser.Drop_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_table_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_table_function([NotNull] BigQueryParser.Drop_table_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_procedure([NotNull] BigQueryParser.Drop_procedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_row_access_policy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_row_access_policy([NotNull] BigQueryParser.Drop_row_access_policyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_capacity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_capacity([NotNull] BigQueryParser.Drop_capacityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_reservation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_reservation([NotNull] BigQueryParser.Drop_reservationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_assignment([NotNull] BigQueryParser.Drop_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_search_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_search_index([NotNull] BigQueryParser.Drop_search_indexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.drop_vector_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_vector_index([NotNull] BigQueryParser.Drop_vector_indexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.view_column_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitView_column_name_list([NotNull] BigQueryParser.View_column_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.view_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitView_column([NotNull] BigQueryParser.View_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_constraint_definitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_constraint_definitions([NotNull] BigQueryParser.Column_constraint_definitionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_constraint_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_constraint_definition([NotNull] BigQueryParser.Column_constraint_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_definition([NotNull] BigQueryParser.Column_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.primary_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_key([NotNull] BigQueryParser.Primary_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.foreign_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeign_key([NotNull] BigQueryParser.Foreign_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.foreign_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeign_reference([NotNull] BigQueryParser.Foreign_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.create_schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_schema([NotNull] BigQueryParser.Create_schemaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_expression([NotNull] BigQueryParser.Query_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.query_expr_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_expr_tail([NotNull] BigQueryParser.Query_expr_tailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.set_operation_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_operation_tail([NotNull] BigQueryParser.Set_operation_tailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.non_recursive_cte"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_recursive_cte([NotNull] BigQueryParser.Non_recursive_cteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.recursive_cte"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecursive_cte([NotNull] BigQueryParser.Recursive_cteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.recursive_union_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecursive_union_operation([NotNull] BigQueryParser.Recursive_union_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect([NotNull] BigQueryParser.SelectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.group_by_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_by_specification([NotNull] BigQueryParser.Group_by_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.grouping_sets_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_sets_specification([NotNull] BigQueryParser.Grouping_sets_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.grouping_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_list([NotNull] BigQueryParser.Grouping_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.grouping_list_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_list_item([NotNull] BigQueryParser.Grouping_list_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.cube_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCube_specification([NotNull] BigQueryParser.Cube_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.groupable_item_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupable_item_set([NotNull] BigQueryParser.Groupable_item_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.rollup_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRollup_specification([NotNull] BigQueryParser.Rollup_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.window_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_clause([NotNull] BigQueryParser.Window_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.named_window_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamed_window_expression([NotNull] BigQueryParser.Named_window_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.window_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_specification([NotNull] BigQueryParser.Window_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.window_frame_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_frame_clause([NotNull] BigQueryParser.Window_frame_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.frame_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_start([NotNull] BigQueryParser.Frame_startContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.frame_between"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_between([NotNull] BigQueryParser.Frame_betweenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.frame_end_a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_end_a([NotNull] BigQueryParser.Frame_end_aContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.frame_end_b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_end_b([NotNull] BigQueryParser.Frame_end_bContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.frame_end_c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_end_c([NotNull] BigQueryParser.Frame_end_cContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.differential_privacy_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDifferential_privacy_clause([NotNull] BigQueryParser.Differential_privacy_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.from_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_clauses([NotNull] BigQueryParser.From_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.from_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_clause([NotNull] BigQueryParser.From_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.from_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_item([NotNull] BigQueryParser.From_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.unnest_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnnest_operator([NotNull] BigQueryParser.Unnest_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.cross_join_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCross_join_operator([NotNull] BigQueryParser.Cross_join_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.condition_join_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_join_operator([NotNull] BigQueryParser.Condition_join_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.join_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_condition([NotNull] BigQueryParser.Join_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.on_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOn_clause([NotNull] BigQueryParser.On_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.using_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsing_clause([NotNull] BigQueryParser.Using_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.pivot_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPivot_operator([NotNull] BigQueryParser.Pivot_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.unpivot_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnpivot_operator([NotNull] BigQueryParser.Unpivot_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.single_column_unpivot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_column_unpivot([NotNull] BigQueryParser.Single_column_unpivotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.multi_column_unpivot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulti_column_unpivot([NotNull] BigQueryParser.Multi_column_unpivotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.columns_to_unpivot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumns_to_unpivot([NotNull] BigQueryParser.Columns_to_unpivotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.column_sets_to_unpivot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_sets_to_unpivot([NotNull] BigQueryParser.Column_sets_to_unpivotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.tablesample_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTablesample_operator([NotNull] BigQueryParser.Tablesample_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.option_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption_parameters([NotNull] BigQueryParser.Option_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.option_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption_parameter([NotNull] BigQueryParser.Option_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.select_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_list([NotNull] BigQueryParser.Select_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.select_list_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_list_item([NotNull] BigQueryParser.Select_list_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.select_all"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_all([NotNull] BigQueryParser.Select_allContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] BigQueryParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressions([NotNull] BigQueryParser.ExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.case_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_expression([NotNull] BigQueryParser.Case_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.coalesce"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCoalesce([NotNull] BigQueryParser.CoalesceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.if_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_([NotNull] BigQueryParser.If_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.ifnull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfnull([NotNull] BigQueryParser.IfnullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.nullif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullif([NotNull] BigQueryParser.NullifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.expressions_as_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressions_as_alias([NotNull] BigQueryParser.Expressions_as_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.expressions_asc_desc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressions_asc_desc([NotNull] BigQueryParser.Expressions_asc_descContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] BigQueryParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_literal([NotNull] BigQueryParser.Numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.big_numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBig_numeric_literal([NotNull] BigQueryParser.Big_numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.array_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_literal([NotNull] BigQueryParser.Array_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.struct_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_literal([NotNull] BigQueryParser.Struct_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type([NotNull] BigQueryParser.Data_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.any_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_identifier([NotNull] BigQueryParser.Any_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_literal([NotNull] BigQueryParser.String_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.date_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate_literal([NotNull] BigQueryParser.Date_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.time_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTime_literal([NotNull] BigQueryParser.Time_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.datetime_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetime_literal([NotNull] BigQueryParser.Datetime_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.timestamp_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimestamp_literal([NotNull] BigQueryParser.Timestamp_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.range_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_literal([NotNull] BigQueryParser.Range_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.interval_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterval_literal([NotNull] BigQueryParser.Interval_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.json_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJson_literal([NotNull] BigQueryParser.Json_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.byte_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitByte_literal([NotNull] BigQueryParser.Byte_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] BigQueryParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.as_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAs_alias([NotNull] BigQueryParser.As_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] BigQueryParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] BigQueryParser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.function_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_arguments([NotNull] BigQueryParser.Function_argumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.function_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_expressions([NotNull] BigQueryParser.Function_expressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.function_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_expression([NotNull] BigQueryParser.Function_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.optional_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptional_clauses([NotNull] BigQueryParser.Optional_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.limit_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimit_clause([NotNull] BigQueryParser.Limit_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.order_by_keys"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_keys([NotNull] BigQueryParser.Order_by_keysContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.order_by_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_key([NotNull] BigQueryParser.Order_by_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.window_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_function([NotNull] BigQueryParser.Window_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.over_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOver_clause([NotNull] BigQueryParser.Over_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.format_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormat_clause([NotNull] BigQueryParser.Format_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.path_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath_expressions([NotNull] BigQueryParser.Path_expressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.path_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath_expression([NotNull] BigQueryParser.Path_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.as_column_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAs_column_names([NotNull] BigQueryParser.As_column_namesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.as_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAs_column_name([NotNull] BigQueryParser.As_column_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReserved([NotNull] BigQueryParser.ReservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BigQueryParser.datetime_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetime_part([NotNull] BigQueryParser.Datetime_partContext context);
}
} // namespace BigO.BigQuery.Parser
